workspaceName=dbvr-ce
featuresPaths=\
  dbeaver/features;\
  dbvr/features;
bundlesPaths=\
  dbeaver-common/modules;\
  dbeaver/plugins;\
  dbeaver/test;\
  dbeaver-jdbc-libsql;\
  dbvr/bundles;\
  dbvr/test;
repositories=\
  https://repo.dbeaver.net/p2/ce/latest/;\
  https://download.eclipse.org/releases/${eclipse-version}/;
testLibraries=\
  org.junit;\
  org.mockito.mockito-core;\
  junit-jupiter-api;\
  org.opentest4j;\
  org.hamcrest.core
productsPaths=\
  dbvr/product/community/dbvr.product;\
  dbvr/product/community-unittest/dbvr-unittest.product;\
  dbeaver/product/community/DBeaver.product;
ideaConfigurationFilesPaths=\
  dbvr/.ide/.idea
optionalFeatureRepositories=\
  dbeaver/product/repositories
